### ISSUE TITLE
Paper-elements not working properly on IE 9

### ISSUE THREAD

**Issue by shailesh17mar** [fballiano/polymer-full#2]
I know you guys do not support ie 9 officially but, I need to get it working on ie 9 as well. Most of the elements work but, checkbox, radio button and some other elements do not work properly.

i am getting this error for every other element 
"Unable to set property '**wrapper8e3dd93a60**' of undefined or null reference"

Can you guide me what is the conceptual problem behind this so, that I may try to sort out this issue.

**Comment by fballiano** [comment]
Hi, I'm sorry but you should open the issue on the paper-checkbox github repository cause i just build the bundle but i don't work on the polymer library itself

thank you!
